# Generated by Django 5.2.1 on 2025-05-26 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de avalição')),
            ],
            options={
                'verbose_name': 'Tipo avaliação',
                'verbose_name_plural': 'Tipos avaliações',
            },
        ),
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da turma')),
                ('periodo', models.CharField(max_length=100, verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacoes',
            options={'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='curso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos'),
        ),
        migrations.AddField(
            model_name='avaliacoes',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplinas'),
        ),
        migrations.CreateModel(
            name='DiciplinaCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da disciplina do curso')),
                ('carga_horaria', models.CharField(max_length=100, verbose_name='Carga horaria')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.periodocurso', verbose_name='Periodo')),
            ],
            options={
                'verbose_name': 'Diciplina curso',
                'verbose_name_plural': 'Disciplinas curso',
            },
        ),
        migrations.CreateModel(
            name='Frequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_faltas', models.CharField(max_length=100, verbose_name='Faltas')),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplinas')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoas', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Frequência',
                'verbose_name_plural': 'Frequências',
            },
        ),
        migrations.CreateModel(
            name='Ocorrencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('data', models.DateField(verbose_name='Data')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplinas')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pessoas', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
            },
        ),
    ]
