# Generated by Django 5.2.1 on 2025-06-03 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tipoavaliacao_turmas_alter_avaliacoes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacoes',
            name='curso',
            field=models.ForeignKey(default=54353, on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacoes',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.disciplinas', verbose_name='Disciplinas'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cursos', verbose_name='Cursos'),
        ),
    ]
